stages:
  - build
  - dockerize
  - deploy

variables:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: tiim32/iti0302-2024

build:
  stage: build
  image: gradle:jdk21
  services:
    - name: postgres:14.1
      alias: postgres
  variables:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: docker
  script:
    - chmod +x ./gradlew
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - branches


dockerize:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - |
      echo "DOCKER_REGISTRY: $DOCKER_REGISTRY"
      echo "DOCKER_IMAGE: $DOCKER_IMAGE"
      echo "CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA"
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
      docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE-$CI_COMMIT_SHORT_SHA .
      docker push $DOCKER_REGISTRY/$DOCKER_IMAGE-$CI_COMMIT_SHORT_SHA
      docker tag $DOCKER_REGISTRY/$DOCKER_IMAGE-$CI_COMMIT_SHORT_SHA $DOCKER_REGISTRY/$DOCKER_IMAGE
      docker push $DOCKER_REGISTRY/$DOCKER_IMAGE
  only:
    - main


deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - || echo "Failed to add SSH key"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
      cd /opt/iti0302/postgres &&
      sudo docker-compose down &&
      sudo docker-compose pull &&
      sudo docker-compose up -d &&
      cd /opt/iti0302/backend &&
      sudo docker-compose down &&
      sudo docker-compose pull &&
      sudo docker-compose up -d"
  only:
    - main
